Repository EnMasseProject/enmasse, pull requests merged in 2018-04, with the labels that each got.

#1152 Extend selenium interface
  systemtests/src/main/java/io/enmasse/systemtest/selenium/ISeleniumProvider.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsolePlansTest.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebSocketBrowserTest.java
Labels: Do Not Merge, status/WIP

#1156 Dependency injection + refactor
  systemtests/src/main/java/io/enmasse/systemtest/AddressApiClient.java
  systemtests/src/main/java/io/enmasse/systemtest/KeycloakClient.java
  systemtests/src/main/java/io/enmasse/systemtest/KeycloakCredentials.java
  systemtests/src/main/java/io/enmasse/systemtest/PlansProvider.java
  systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java
  systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpClientFactory.java
  systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpConnectOptions.java
  systemtests/src/main/java/io/enmasse/systemtest/mqtt/MqttClient.java
  systemtests/src/main/java/io/enmasse/systemtest/mqtt/MqttClientFactory.java
  systemtests/src/main/java/io/enmasse/systemtest/resolvers/ArtemisManagementParameterResolver.java
  systemtests/src/main/java/io/enmasse/systemtest/selenium/ConsoleWebPage.java
  systemtests/src/main/java/io/enmasse/systemtest/selenium/RheaWebPage.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/TestBaseWithShared.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/auth/AuthenticationTestBase.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/authz/AuthorizationTestBase.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClientTestBase.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsolePlansTest.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java
  systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebSocketBrowserTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/SmokeTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/TopicTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/auth/AuthenticationTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/artemis/MsgPatternsTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/openwire/MsgPatternsTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/proton/java/MsgPatternsTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/proton/python/MsgPatternsTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/rhea/MsgPatternsTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/web/ChromeWebConsoleTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java
  systemtests/src/test/java/io/enmasse/systemtest/common/api/AddressControllerApiTest.java
  systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java
  systemtests/src/test/java/io/enmasse/systemtest/marathon/MarathonTestBase.java
  systemtests/src/test/java/io/enmasse/systemtest/standard/PlansTest.java
  systemtests/src/test/java/io/enmasse/systemtest/standard/WithoutMqttTest.java
  systemtests/src/test/java/io/enmasse/systemtest/standard/clients/proton/java/MsgPatternsTest.java
  systemtests/src/test/java/io/enmasse/systemtest/standard/clients/proton/python/MsgPatternsTest.java
  systemtests/src/test/java/io/enmasse/systemtest/standard/clients/rhea/MsgPatternsTest.java
  systemtests/src/test/java/io/enmasse/systemtest/standard/web/ChromeWebConsoleTest.java
  systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
Labels: Do Not Merge

#1171 Message load tests
  systemtests/src/main/java/io/enmasse/systemtest/JmsProvider.java
  systemtests/src/main/java/io/enmasse/systemtest/clients/AbstractClient.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/QueueTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/TopicTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/jms/QueueTest.java
  systemtests/src/test/java/io/enmasse/systemtest/brokered/jms/TopicTest.java
Labels: test development
